package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import androidx.core.content.FileProvider
import com.example.data.model.Dossier
import com.example.data.model.StudyTopicAddon
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExporter {

    fun exportAndShare(context: Context, dossier: Dossier, addons: List<StudyTopicAddon>) {
        try {
            val pdfFile = generatePdfFile(context, dossier, addons)
            val authority = "com.example.fileprovider"
            val fileUri = FileProvider.getUriForFile(context, authority, pdfFile)
            sharePdf(context, fileUri, dossier.topic)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun generatePdfFile(context: Context, dossier: Dossier, addons: List<StudyTopicAddon>): File {
        val pdfDocument = PdfDocument()
        var pageCount = 0
        var currentPage: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var currentY = 55f

        // Page limit configs
        val pageWidth = 595
        val pageHeight = 842
        val leftMargin = 40f
        val rightMargin = 40f
        val printableWidth = pageWidth - leftMargin - rightMargin // 515f
        val bottomLimit = 780f

        fun drawRunningHeader(c: Canvas) {
            val headerPaint = Paint().apply {
                color = Color.parseColor("#3F51B5")
                isAntiAlias = true
                textSize = 9f
                typeface = Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)
            }
            val linePaint = Paint().apply {
                color = Color.parseColor("#E0E0E0")
                strokeWidth = 1f
            }
            c.drawText("CRAMTIME AI COPILOT STUDY HUB", leftMargin, 35f, headerPaint)
            c.drawLine(leftMargin, 40f, pageWidth - rightMargin, 40f, linePaint)

            val footerPaint = Paint().apply {
                color = Color.parseColor("#9E9E9E")
                isAntiAlias = true
                textSize = 8f
            }
            c.drawLine(leftMargin, 800f, pageWidth - rightMargin, 800f, linePaint)
            c.drawText("Page $pageCount", pageWidth - rightMargin - footerPaint.measureText("Page $pageCount"), 815f, footerPaint)
            c.drawText("Generated by CramTime AI Study Assistant", leftMargin, 815f, footerPaint)
        }

        fun startNewPage() {
            currentPage?.let {
                pdfDocument.finishPage(it)
            }

            pageCount++
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageCount).create()
            val page = pdfDocument.startPage(pageInfo)
            currentPage = page
            canvas = page.canvas
            currentY = 55f

            canvas?.let { drawRunningHeader(it) }
        }

        fun drawParagraph(
            text: String,
            isBold: Boolean = false,
            size: Float = 10f,
            colorHex: String = "#212121",
            isMonospace: Boolean = false,
            xOffset: Float = leftMargin,
            width: Int = printableWidth.toInt(),
            spacingAfter: Float = 4f,
            leftBarColorHex: String? = null
        ) {
            if (text.isEmpty()) return

            val textPaint = TextPaint().apply {
                isAntiAlias = true
                this.color = Color.parseColor(colorHex)
                this.textSize = size
                val style = if (isBold) Typeface.BOLD else Typeface.NORMAL
                this.typeface = if (isMonospace) {
                    Typeface.create(Typeface.MONOSPACE, style)
                } else {
                    Typeface.create(Typeface.DEFAULT, style)
                }
            }

            val staticLayout = StaticLayout.Builder.obtain(text, 0, text.length, textPaint, width)
                .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                .setLineSpacing(0f, 1.15f)
                .setIncludePad(false)
                .build()

            val lineCount = staticLayout.lineCount
            for (i in 0 until lineCount) {
                val lineTop = staticLayout.getLineTop(i)
                val lineBottom = staticLayout.getLineBottom(i)
                val lineHeight = lineBottom - lineTop

                if (currentY + lineHeight > bottomLimit) {
                    startNewPage()
                }

                canvas?.let { c ->
                    leftBarColorHex?.let { barColor ->
                        val barPaint = Paint().apply {
                            color = Color.parseColor(barColor)
                            style = Paint.Style.FILL
                        }
                        c.drawRect(xOffset - 12f, currentY, xOffset - 9f, currentY + lineHeight, barPaint)
                    }

                    c.save()
                    c.translate(xOffset, currentY)
                    c.clipRect(0f, 0f, width.toFloat(), lineHeight.toFloat())
                    c.translate(0f, -lineTop.toFloat())
                    staticLayout.draw(c)
                    c.restore()
                }

                currentY += lineHeight
            }
            currentY += spacingAfter
        }

        // Initialize the first page
        startNewPage()

        // 1. Cover Header
        drawParagraph(
            text = "STUDY DOSSIER & COMPREHENSIVE OUTLINE",
            isBold = true,
            size = 11f,
            colorHex = "#3F51B5",
            isMonospace = true,
            spacingAfter = 6f
        )

        drawParagraph(
            text = dossier.topic.uppercase(Locale.getDefault()),
            isBold = true,
            size = 20f,
            colorHex = "#1A237E",
            spacingAfter = 8f
        )

        // Meta Banner Box
        val dateText = SimpleDateFormat("MMM dd, yyyy - hh:mm a", Locale.getDefault()).format(Date(dossier.timestamp))
        val metaString = "MODE: ${dossier.mode.uppercase()}  |  TARGET: ${dossier.deadlineText}  |  CREATED: $dateText"
        
        drawParagraph(
            text = metaString,
            isBold = true,
            size = 9f,
            colorHex = "#455A64",
            isMonospace = true,
            spacingAfter = 16f
        )

        // Draw Cover Accent Divider Line
        canvas?.let { c ->
            val accentPaint = Paint().apply {
                color = Color.parseColor("#3F51B5")
                style = Paint.Style.FILL
            }
            c.drawRect(leftMargin, currentY, pageWidth - rightMargin, currentY + 3f, accentPaint)
        }
        currentY += 18f

        // Parse syllabus JSON
        val jsonObject = try {
            JSONObject(dossier.materialText)
        } catch (e: Exception) {
            JSONObject()
        }

        // Company Briefing for Interview Mode
        if (dossier.mode == "Interview" && dossier.companyBriefing.isNotBlank()) {
            drawParagraph(
                text = "COMPANY & ROLE BRIEFING",
                isBold = true,
                size = 12f,
                colorHex = "#1A237E",
                spacingAfter = 4f
            )
            drawParagraph(
                text = dossier.companyBriefing,
                size = 10f,
                colorHex = "#37474F",
                spacingAfter = 16f,
                leftBarColorHex = "#78909C"
            )
        }

        // Presentation details
        if (dossier.mode == "Presentation") {
            drawParagraph(
                text = "SLIDE OUTLINE CONFIGURATION",
                isBold = true,
                size = 12f,
                colorHex = "#1A237E",
                spacingAfter = 4f
            )
            drawParagraph(
                text = "Target Length: ${dossier.slideCount} Slides",
                size = 10f,
                colorHex = "#37474F",
                spacingAfter = 16f
            )
        }

        // Core Topics / Syllabus
        val syllabusArray = jsonObject.optJSONArray("syllabus") ?: JSONArray()
        if (syllabusArray.length() > 0) {
            drawParagraph(
                text = "CURATED STUDY SYLLABUS",
                isBold = true,
                size = 14f,
                colorHex = "#1A237E",
                spacingAfter = 10f
            )

            for (idx in 0 until syllabusArray.length()) {
                val obj = syllabusArray.optJSONObject(idx) ?: JSONObject()
                val topicName = obj.optString("topic", "Subtopic Node")
                val importance = obj.optString("importance", "HIGH")
                val content = obj.optString("content", "")
                val aiNotes = obj.optString("studyNotes", "")
                val aiVideos = obj.optJSONArray("youtubeVideos")

                // Topic header & Badge
                val impColor = when (importance.uppercase(Locale.getDefault())) {
                    "CRITICAL" -> "#D32F2F"
                    "HIGH" -> "#E65100"
                    else -> "#00796B"
                }

                drawParagraph(
                    text = "Topic ${idx + 1}: $topicName  [$importance]",
                    isBold = true,
                    size = 12f,
                    colorHex = "#1A237E",
                    spacingAfter = 4f,
                    leftBarColorHex = impColor
                )

                // Subtopic Overview Text
                drawParagraph(
                    text = content,
                    size = 10f,
                    colorHex = "#212121",
                    xOffset = leftMargin + 12f,
                    width = (printableWidth - 12f).toInt(),
                    spacingAfter = 8f
                )

                // AI Copilot Study Guide
                if (aiNotes.isNotBlank()) {
                    drawParagraph(
                        text = "AI COPILOT STUDY NOTES & CHEAT SHEET:",
                        isBold = true,
                        size = 9f,
                        colorHex = "#3F51B5",
                        isMonospace = true,
                        xOffset = leftMargin + 12f,
                        width = (printableWidth - 12f).toInt(),
                        spacingAfter = 2f
                    )
                    drawParagraph(
                        text = aiNotes,
                        size = 9.5f,
                        colorHex = "#37474F",
                        xOffset = leftMargin + 24f,
                        width = (printableWidth - 24f).toInt(),
                        spacingAfter = 8f,
                        leftBarColorHex = "#C5CAE9"
                    )
                }

                // AI Recommended YouTube Tutorials
                if (aiVideos != null && aiVideos.length() > 0) {
                    drawParagraph(
                        text = "AI RECOMMENDED YOUTUBE TUTORIALS (TAP TO SEARCH):",
                        isBold = true,
                        size = 9f,
                        colorHex = "#D32F2F",
                        isMonospace = true,
                        xOffset = leftMargin + 12f,
                        width = (printableWidth - 12f).toInt(),
                        spacingAfter = 2f
                    )

                    for (vIdx in 0 until aiVideos.length()) {
                        val vObj = aiVideos.optJSONObject(vIdx)
                        if (vObj != null) {
                            val vTitle = vObj.optString("title", "")
                            val vUrl = vObj.optString("url", "")
                            if (vTitle.isNotBlank()) {
                                drawParagraph(
                                    text = "• $vTitle \n  Link: $vUrl",
                                    size = 9f,
                                    colorHex = "#D32F2F",
                                    xOffset = leftMargin + 24f,
                                    width = (printableWidth - 24f).toInt(),
                                    spacingAfter = 4f
                                )
                            }
                        }
                    }
                    currentY += 4f
                }

                // Personal Study Addons (Notes and YouTube References added by the user)
                val userAddon = addons.find { it.topicName == topicName }
                if (userAddon != null) {
                    val userNotes = userAddon.notes
                    val userLinks = userAddon.youtubeLinks.split("\n").filter { it.isNotBlank() }

                    if (userNotes.isNotBlank()) {
                        drawParagraph(
                            text = "MY PERSONAL STUDY NOTES:",
                            isBold = true,
                            size = 9f,
                            colorHex = "#00796B",
                            isMonospace = true,
                            xOffset = leftMargin + 12f,
                            width = (printableWidth - 12f).toInt(),
                            spacingAfter = 2f
                        )
                        drawParagraph(
                            text = userNotes,
                            size = 9.5f,
                            colorHex = "#212121",
                            xOffset = leftMargin + 24f,
                            width = (printableWidth - 24f).toInt(),
                            spacingAfter = 8f,
                            leftBarColorHex = "#B2DFDB"
                        )
                    }

                    if (userLinks.isNotEmpty()) {
                        drawParagraph(
                            text = "MY YOUTUBE STUDY REFERENCES:",
                            isBold = true,
                            size = 9f,
                            colorHex = "#00796B",
                            isMonospace = true,
                            xOffset = leftMargin + 12f,
                            width = (printableWidth - 12f).toInt(),
                            spacingAfter = 2f
                        )
                        userLinks.forEach { link ->
                            drawParagraph(
                                text = "• $link",
                                size = 9f,
                                colorHex = "#004D40",
                                xOffset = leftMargin + 24f,
                                width = (printableWidth - 24f).toInt(),
                                spacingAfter = 4f
                            )
                        }
                    }
                }

                // Space between topics
                currentY += 12f
            }
        }

        // Finish last page
        currentPage?.let {
            pdfDocument.finishPage(it)
        }

        // Write to cache directory
        val cacheDir = context.cacheDir
        val safeTopicName = dossier.topic.replace("[^a-zA-Z0-9]".toRegex(), "_")
        val pdfFile = File(cacheDir, "CramTime_${safeTopicName}.pdf")
        val fos = FileOutputStream(pdfFile)
        pdfDocument.writeTo(fos)
        fos.close()
        pdfDocument.close()

        return pdfFile
    }

    private fun sharePdf(context: Context, fileUri: Uri, topic: String) {
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, fileUri)
            putExtra(Intent.EXTRA_SUBJECT, "CramTime Study Dossier - $topic")
            putExtra(Intent.EXTRA_TEXT, "Here is my generated study dossier, copilot notes, and summaries for: $topic")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Export & Share Study PDF"))
    }
}
